version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    branches:
      only:
        - master
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-
      - run:
          name: Node Global dependencies
          command: sudo npm install -g firebase-tools
      - save_cache:
          paths:
            - /usr/local/lib/node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Node dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Deploy
          command: firebase deploy --project $FIREBASE_PJ --token $FIREBASE_TOKEN
